name: DeEEP Resolution Proposal
description: Suggest a Resolution for the DeEEP Network
title: "[DR]: "
labels: ["resolution"]
assignees:
  - anthonyra
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make DeEEP Network better!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists including closed issues.
      options:
      - label: I have searched for an existing issue(s)
        required: true
  - type: checkboxes
    attributes:
      label: Have you discussed this in the Discord yet?
      description: Not required but getting additional discussion on your Resolution is recommended.
      options:
      - label: I have discussed this Resolution in the [Discord](https://discord.gg/deeep-network)
        required: false
  - type: input
    id: discord-discussion
    attributes:
      label: Discord Discussion
      description: Please provide a Message Link to the Discord discussion or thread.
      placeholder: ex. https://discord.com/channels/1247281918660055223/1251215470204424193/1254903609255264271
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need to?
      placeholder: ex. email@example.com, discord handle
    validations:
      required: false
  - type: dropdown
    id: change-type
    attributes:
      label: Select the type of change?
      description: |
        All resolutions should only consist of one type of change. 
        If it doesn't, changing the scope or size of the Resolution is recommended.
        Provide a reason in the Resolution below if it's not possible.
      multiple: true
      options:
        - Blockchain Configuration
        - Smart Contract
        - Architecture
        - Infrastructure
        - New Feature
        - Tokenomics
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why does DeEEP Network need this Resolution?
      placeholder: |
        Is there an issue it's trying to solve?
        Is it a feature that'll make DeEEP Network better?
        Who will benefit from this?
      value: "What's the motivation for this Resolution?"
  - type: textarea
    id: resolution
    attributes:
      label: Implementation Details
      description: Will be rendered in Markdown, allowing you to utilize its styling.
      value: |
        Should be written in Markdown and should be a standalone document as much as possible.
        Links can be used but sparingly.

        ## Budget / Proposal Fund

        It all takes effort and money, explain how you propose to get your proposal completed.
        Also list the sources you envision this coming from.

        ## Timeline
        
        How long would it take to implement? Does it require Core Team contribution to estimation?

        ## Alternatives

        Are they any alternatives to this Resolution. Including implementation, development, or scope?

        ## Implementation Plan

        Is there development and resources set aside to develop and implement the Resolution?
        IF so list responsible parties here.
